### ISSUE TITLE
Setting contact reader payload capacity

### ISSUE THREAD

**Issue by amessara-billettiqueservices** [eclipse-keyple/keyple-card-calypso-java-lib#111]
Hello team,

We have an issue with the bluebird reader that does not handle correctly big commands to the contact reader (digest multi). I was looking for a way to limit the payload size for that reader in the plugin but I could not find any satisfactory solution.
In the version we are using, the `CalypsoExtensionService` has anticipated this need and already has an interface for this `ContextSetting.setContactReaderPayloadCapacity`. In order to use that, this call has be done by the application using the calypsoExtension depending on the reader it is connected to. I don't know if this kind of operation should be left to the responsibility of the application. I think it should be automatically done when creating the transaction manager. Reader could provide that payload capacity and should be set in CalypsoExtensionService when creating a transaction with that reader.

Regards,
Aghilas MESSARA

**Comment by jeanpierrefortune** [comment]
Hello Aghilas,

Thank you for your participation and for bringing this issue to our attention.

The addition of the `setContactReaderPayloadCapacity` method effectively comes from the limitation encountered with Bluebird terminals.
It would indeed be ideal for the responsibility of defining this capacity to fall to the plugin, as it is a hardware-specific limitation.

However, we decided not to integrate a negotiation mechanism for this in the Plugin API because in this case the Card API would also have had to be upgraded, as it is this API that is seen by the card extensions (the capacity limitation must be known at command build time).

The Card API being one of the basis of the terminal certification process planned by CNA, it cannot incorporate non-compliance with standards.

Best regards,
Jean-Pierre Fortune

**Comment by andrei-cristea** [comment]
Hi Aghilas,

We're closing this issue, but feel free to reopen it if you need to.

Regards
